#!/usr/bin/env bash
# Startup-script fragment for an Air Cloud automation that needs `jb` (JetBrains/jb-cli).
# Paste inline into the environment configuration's startup script (PATCH, not PUT —
# PUT resets startup_script to NULL; jcp-air/cloud/backend/docs/environment-configurations.md:51).
#
# Two things must be true before this can work, and neither is about GitHub auth:
#
#  1. EGRESS. The env config defaults to networkAccess=RESTRICTED with [WELL_KNOWN]
#     (environment-configurations.md:229). Neither host below is a system domain, so both
#     must be added as CUSTOM domains on the config:
#         jb-cli.labs.jb.gg      the installer + archive origin
#         storage.googleapis.com the 302 target (15-min V4 pre-signed GCS URL)
#     jb-cli.labs.jb.gg is on the INTERNAL domain (internal-nginx, VPN-only): allowlisting it
#     is necessary but may not be sufficient, because the workspace also has to route to it.
#     probe_reachability below is what tells the two apart — read its output first.
#
#  2. unzip. The installer hard-requires `unzip` or `bsdtar` and dies otherwise
#     ("neither 'unzip' nor 'bsdtar' found (needed to extract the bundle zip)").
#     The Air workspace image ships neither, and sudo is password-gated. install_unzip_shim
#     below puts a python3-backed stand-in on PATH first. Delete it once the image ships unzip.
#
# Optional variable, only for the GitHub fallback (see install_jb_from_github):
#   JB_CLI_GITHUB_TOKEN  secret  a PAT with repo:read from a JetBrains org member.
#     jetbrains-air[bot] CANNOT stand in: a GitHub App token reads an INTERNAL repo only if
#     the app is installed on that repo. Leave unset to skip the fallback entirely.

set -uo pipefail
log() { printf 'startup: %s\n' "$*"; }
err() { printf 'startup: ERROR: %s\n' "$*" >&2; }

readonly PROFILE_HOOK="$HOME/.air-jb-cli-env.sh"
readonly JB_SITE="https://jb-cli.labs.jb.gg"
readonly JB_HOME="$HOME/.jb-cli"
readonly JB_LAUNCHER="$JB_HOME/bin/jb"

# --- 0. PATH hook -------------------------------------------------------------
# One hook, sourced from both shells. JB_NO_AUTO_UPDATE is set for an automation on purpose:
# a release build otherwise checks for a newer version on every run (4 h throttle) in a
# detached process, which needs the same egress and adds nothing to a one-shot task.
init_profile_hook() {
    cat > "$PROFILE_HOOK" <<'PROFILE_EOF'
# jb-cli automation environment, regenerated by the startup script.
export JB_NO_AUTO_UPDATE=1
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) export PATH="$HOME/.local/bin:$PATH" ;;
esac
case ":$PATH:" in
  *":$HOME/.jb-cli/bin:"*) ;;
  *) export PATH="$HOME/.jb-cli/bin:$PATH" ;;
esac
PROFILE_EOF

    local profile
    for profile in "$HOME/.bashrc" "$HOME/.profile"; do
        touch "$profile" 2>/dev/null || continue
        grep -Fq "$PROFILE_HOOK" "$profile" 2>/dev/null && continue
        printf '\n[ -f %q ] && . %q\n' "$PROFILE_HOOK" "$PROFILE_HOOK" >> "$profile"
    done
    # shellcheck source=/dev/null
    . "$PROFILE_HOOK"
}

# --- 1. unzip stand-in --------------------------------------------------------
# Must run BEFORE the installer: it probes for unzip/bsdtar up front and dies if neither
# is on PATH. Same shim as the monorepo fragment; the installer's call is
# `unzip -q <archive> -d <staging>`, which is exactly the form this supports.
install_unzip_shim() {
    command -v unzip > /dev/null 2>&1 && { log "unzip already present"; return 0; }
    command -v bsdtar > /dev/null 2>&1 && { log "bsdtar present; installer will use it"; return 0; }
    command -v python3 > /dev/null 2>&1 || { err "no unzip, no bsdtar, no python3; cannot extract the bundle"; return 1; }

    mkdir -p "$HOME/.local/bin"
    cat > "$HOME/.local/bin/unzip" <<'SHIM_EOF'
#!/usr/bin/env bash
# Minimal unzip stand-in over python3's zipfile. Supports the common
# `unzip [-q|-qq|-o] archive.zip [-d dir]` form only; anything else exits 2 rather
# than silently extracting the wrong thing.
set -uo pipefail
archive= dest=.
while [ $# -gt 0 ]; do
  case "$1" in
    -q|-qq|-o|-oq|-qo) shift ;;
    -d) dest="$2"; shift 2 ;;
    -*) echo "unzip shim: unsupported option $1" >&2; exit 2 ;;
    *)  if [ -z "$archive" ]; then archive="$1"; shift; else
          echo "unzip shim: extracting a file subset is unsupported" >&2; exit 2; fi ;;
  esac
done
[ -n "$archive" ] || { echo "unzip shim: no archive given" >&2; exit 2; }
mkdir -p "$dest" && exec python3 -m zipfile -e "$archive" "$dest"
SHIM_EOF
    chmod +x "$HOME/.local/bin/unzip"
    log "installed a python3-backed unzip shim at $HOME/.local/bin/unzip"
}

# --- 2. Prove the egress before blaming the install ---------------------------
# The whole point of this fragment. Three outcomes, and they need different fixes:
#   site 200 + gcs 2xx/4xx  -> egress is fine, install away
#   site 000                -> DNS/route/allowlist. Add the custom domains; if they are
#                              already there, the workspace cannot route to the internal
#                              host at all and no allowlist entry will change that.
#   site 200 + gcs 000      -> only storage.googleapis.com is missing from the allowlist.
# 000 is curl's "never got a response" — a blocked or unroutable host, not an HTTP error.
probe_reachability() {
    local site_code gcs_code
    site_code=$(curl -sS -o /dev/null -m 15 -w '%{http_code}' "$JB_SITE/version.json" 2>/dev/null)
    gcs_code=$(curl -sS -o /dev/null -m 15 -w '%{http_code}' "https://storage.googleapis.com/" 2>/dev/null)
    log "  $site_code  $JB_SITE/version.json"
    log "  $gcs_code  https://storage.googleapis.com/"

    if [[ $site_code != 200 ]]; then
        err "$JB_SITE is not reachable from this workspace (got '$site_code').
  It is an internal host behind internal-nginx. Add jb-cli.labs.jb.gg and
  storage.googleapis.com as custom domains on the environment configuration; if they are
  already allowlisted, the workspace has no route to the internal network and the supported
  installer cannot be used here. Ask in #jb-cli (Slack C0AEQ4E3Z50) — see issue #79."
        return 1
    fi
    if [[ $gcs_code == 000 ]]; then
        err "storage.googleapis.com is unreachable (000). The site answers installer and archive
  requests with a 302 to a pre-signed bucket URL, so the download will fail even though
  $JB_SITE responds. Add storage.googleapis.com as a custom domain."
        return 1
    fi
    log "egress to the jb-cli site and the release bucket is open"
}

# --- 3. The supported install -------------------------------------------------
# stdout of the installer is exactly one line: the absolute launcher path. Everything else
# goes to stderr, which is why the command substitution is safe to compare against.
# ~290 MB for the linux-x64 bundle (self-contained JDK) — expect this step to dominate.
install_jb_supported() {
    local printed
    printed=$(curl -fsSL -m 120 "$JB_SITE/install.sh" | sh) || { err "the jb-cli installer failed"; return 1; }
    if [[ $printed != "$JB_LAUNCHER" ]]; then
        err "installer printed '$printed', expected '$JB_LAUNCHER'"
        return 1
    fi
    log "jb installed at $JB_LAUNCHER"
}

# --- 4. Fallback: GitHub release asset ----------------------------------------
# Unsupported on purpose — jb-cli is INTERNAL precisely so that installing it needs no
# GitHub token (docs/INSTALL_AND_UPDATE.md, "Why a bucket behind the website"). This exists
# so you can still get a working `jb` while the egress question is being settled, and it
# puts a human PAT in the automation. Skipped unless JB_CLI_GITHUB_TOKEN is set.
install_jb_from_github() {
    [[ -n ${JB_CLI_GITHUB_TOKEN:-} ]] || { log "JB_CLI_GITHUB_TOKEN unset; skipping the GitHub fallback"; return 1; }

    local api="https://api.github.com/repos/JetBrains/jb-cli" tag arch asset asset_id tmp
    tag=$(curl -fsS -m 30 -H "Authorization: Bearer $JB_CLI_GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" "$api/releases/latest" \
          | python3 -c 'import json,sys; print(json.load(sys.stdin)["tag_name"])') \
        || { err "could not read the latest jb-cli release (token rejected, or no egress to api.github.com)"; return 1; }

    case "$(uname -m)" in
        x86_64)          arch="linux-x64" ;;
        aarch64|arm64)   arch="linux-aarch64" ;;
        *) err "unsupported arch $(uname -m)"; return 1 ;;
    esac
    asset="jb-cli-${tag#v}-${arch}.zip"

    asset_id=$(curl -fsS -m 30 -H "Authorization: Bearer $JB_CLI_GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github+json" "$api/releases/tags/$tag" \
               | python3 -c "import json,sys; print(next(a['id'] for a in json.load(sys.stdin)['assets'] if a['name']=='$asset'))") \
        || { err "release $tag has no asset named $asset"; return 1; }

    tmp=$(mktemp -d) || return 1
    log "downloading $asset from release $tag (~290 MB)"
    curl -fsSL -m 900 -H "Authorization: Bearer $JB_CLI_GITHUB_TOKEN" \
         -H "Accept: application/octet-stream" "$api/releases/assets/$asset_id" -o "$tmp/$asset" \
        || { err "asset download failed"; rm -rf "$tmp"; return 1; }

    unzip -q "$tmp/$asset" -d "$tmp/x" || { err "extract failed"; rm -rf "$tmp"; return 1; }

    # Exactly one top-level directory, and the binary sits at its root as `jb` — not bin/jb.
    local unpacked count=0 entry
    for entry in "$tmp"/x/*; do
        [ -e "$entry" ] || continue
        count=$((count + 1)); unpacked="$entry"
    done
    if [[ $count -ne 1 || ! -d ${unpacked:-} ]]; then
        err "unexpected archive layout: expected exactly one top-level directory in $asset"
        rm -rf "$tmp"; return 1
    fi

    # Restore the executable bits, mirroring the real installer. Mandatory here: the
    # python3 zipfile shim does NOT preserve mode (verified — files land 0644), and a
    # 0644 jspawnhelper breaks every subprocess the JVM spawns via POSIX_SPAWN.
    chmod +x "$unpacked/jb" 2>/dev/null || true
    [[ -d $unpacked/bin ]]     && chmod +x "$unpacked/bin"/* 2>/dev/null
    [[ -d $unpacked/jdk/bin ]] && chmod +x "$unpacked/jdk/bin"/* 2>/dev/null
    chmod +x "$unpacked/jdk/lib/jspawnhelper" "$unpacked/jdk/lib/jexec" 2>/dev/null || true
    [[ -x $unpacked/jb ]] || { err "$unpacked/jb missing or not executable after extract"; rm -rf "$tmp"; return 1; }

    # Let the binary own its launcher, exactly as the real installer's last step does.
    # JB_CLI_HOME is passed explicitly: the JVM derives user.home from the passwd entry,
    # not $HOME, so without it the launcher can land somewhere else entirely.
    JB_CLI_HOME="$JB_HOME" "$unpacked/jb" selfinstall < /dev/null >&2 \
        || { err "jb selfinstall failed"; rm -rf "$tmp"; return 1; }
    rm -rf "$tmp"
    [[ -x $JB_LAUNCHER ]] || { err "selfinstall left no launcher at $JB_LAUNCHER"; return 1; }
    log "jb installed at $JB_LAUNCHER via the GitHub fallback (unsupported path)"
}

# --- 5. Verdict ---------------------------------------------------------------
verify_jb() {
    command -v jb > /dev/null 2>&1 || { err "jb is not on PATH after install"; return 1; }
    log "jb --version: $(jb --version 2>&1 | head -1)"
    # Auth is a separate problem: `jb auth login` opens a browser, which an automation has
    # no way to complete. The headless forms are
    #   jb auth login --service jetbrains.team --token <token>
    #   jb auth login --service teamcity --api-key <key>
    # with tokens supplied as secret env-config variables. Tokens land in ~/.jb-cli/tokens/,
    # which is inside $HOME and therefore captured in the snapshot — prefer passing them per
    # run over baking them in. Left out here deliberately: get `jb --version` green first.
    log "installed but NOT authenticated — see jb auth login --service <svc> --token <tok>"
}

init_profile_hook
install_unzip_shim || exit 1
if probe_reachability; then
    install_jb_supported || exit 1
else
    log "falling back to the GitHub release asset"
    install_jb_from_github || { err "no usable install path for jb-cli in this workspace"; exit 1; }
fi
verify_jb || exit 1
log "environment ready"
